name: nhutube
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  lottie: ^2.1.0
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  bloc: ^8.1.0
  flutter_localizations:
    sdk: flutter
  pin_code_fields: ^7.4.0
  angles: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/svgs/
    - assets/languages/en.json
    - assets/languages/vi.json
